### ISSUE TITLE
**bug report** Not verified for use in Firefox and has been disabled

### ISSUE THREAD

**Issue by Bicho-Git** [seansfkelley/synology-download-manager#107]
Hi!
5 may 2019 > Firefox has updated security features and disable add-ons that not verified.
Now **Synology Download Manager** could not be verified for use in Firefox and has been disabled.
macOS High Sierra (10.13.6)
Firefox 66.0.3 (64bit)
Synology Download Manager v0.5.6
DSM 6.2.1-23824 Update 6

Can you fix it?

Thanks in Advance!

Bicho-Git

**Comment by seansfkelley** [comment]
Looks like this was an issue in Firefox 66.0.3 that disabled many extensions and has since [been fixed in 66.04](https://www.mozilla.org/en-US/firefox/66.0.4/releasenotes/). Let me know if upgrading your Firefox doesn't fix it!
