### ISSUE TITLE
Not downloadable from addons.mozilla

### ISSUE THREAD

**Issue by desperado591** [seansfkelley/synology-download-manager#109]
Since the Firefox Addons deactivation last week, my Synology Download Manager is completely gone from Firefox 52.9.0 and even after fixing the addon issue it is impossible to install it again.
When I Try to install it from https://addons.mozilla.org/de/firefox/addon/synology-download-manager/ it says "Download failed. Please check your connection" but of course I am connected to the internet. I also made sure that there is no popup blocker or ad-filter running.
So I tried to save the file on the harddisc and install it from the file, but there it says the file is broken.
Is it possible to obtain the xpi file here on github directly?

**Comment by seansfkelley** [comment]
Hm, I just uninstalled and reinstalled the extension just fine from that link on FF 66.0.4. What do you mean, "after fixing the addon issue"? I wonder if you're seeing the effects of that issue they introduced recently that broke all web extensions.

**Comment by desperado591** [comment]
I installed an Hotfix for the certificate issue and also disabled "xpinstall.signatures.required" in "about:config". Every other addon that I am using is running fine again after that, only the Synology Download Manager stays disappeared and when I try to reinstall it, there is that error message, saying that the download failed.
Unfortunately there is no newer version of Firefox than 52.9.0 for my Windows XP.
Isn´t there a way to download the xpi file manually?

**Comment by desperado591** [comment]
I just tried to install it on another Laptop with Win XP and Firefox 52.9.0 and there was the same behavior: Download failed, please check your connection
So there is definitively something wrong with the download page on Mozilla, at least with Win XP :-(

**Comment by seansfkelley** [comment]
Unfortunately I don't think there's much I can do here because it sounds like this is more of a Firefox bug than mine. Perhaps I'm using some new features that are triggering the bug, but without a Windows machine with XP there's not really any way for me to find out.

It looks like you're able to download the .xpi as a simple file without Firefox trying to install it by right-clicking the download button on https://addons.mozilla.org/de/firefox/addon/synology-download-manager/ and then doing "save link as".

If you want to verify the integrity of your installation, version 0.5.6's .xpi (the latest) has an md5 of `b1f363a64e208fc83b9ce8b525201253`. I confirmed this is identical to the version that I am currently running that's downloaded from the site.

**Comment by desperado591** [comment]
I already tried to download the xpi file with the method you mentioned. But there is also an error message when trying to install the downloaded file saying "This add-on could not be installed as it is broken".
That is why I was asking you to provide the xpi file elsewhere e.g. directly from github, or a link to a website where I can download it, other than the Mozilla website.

**Comment by seansfkelley** [comment]
I suspect there's something else failing here, not the Mozilla site. If you download a copy from addons.mozilla.org (version 0.5.6) and [md5 it](https://support.microsoft.com/en-us/help/889768/how-to-compute-the-md5-or-sha-1-cryptographic-hash-values-for-a-file), you should get `b1f363a64e208fc83b9ce8b525201253` (as noted above). If you do, you have the same code I do and that means there's some kind of bug in the interaction between the extension/browser/OS. If you don't (which would be very surprising indeed), this means that for some reason you aren't getting the right file. Could you try that out for me?

**Comment by desperado591** [comment]
Okay, I downloaded it from addons.mozilla.org by right clicking and "saving link as", which resulted in a file called synology_download_manager-0.5.6-fx.xpi on my hard drive.

Afterwards I installed the File Checksum Integrity Verifier as explained in your given link and run it via comand prompt. This gave me b1f363a64e208fc83b9ce8b525201253, which is the same as you mentioned.

But when I try to install the addon manually from that xpi file it says, that the file is broken ;-(

I did this on 2 different computers running Windows XP, so I am pretty sure it is not a configuration problem, as the 2 computers are really different regarding programs and add ons. 

Your add on worked really fine untill that damn Firefox add on bug :-(

**Comment by seansfkelley** [comment]
Yeah, that's what I figured would happen. This sounds like a bug in Firefox, and given that they recently accidentally broke all extensions on all OSes, I wouldn't be surprised if they had unintentionally broken compatibility with older operating systems like XP. Unfortunately there's not much I can do to help you beyond just saying you should file a bug on Mozilla themselves.

**Comment by desperado591** [comment]
Do you know if there is a special adress at Mozilla where I can complain about that, maybe something they opened just for all the add-on bugs?
Nevertheless I would like to thank you very much for your effort and patience :-)

**Comment by seansfkelley** [comment]
Not beyond the [official bug tracker](https://bugzilla.mozilla.org/home), no.

**Comment by desperado591** [comment]
Just wanted to let you know: It is working again after I tried it again today! :-) I don´t know if they have changed anything, but the main point is, that it is working agein for me!

**Comment by seansfkelley** [comment]
Great! What an unexpected but nice surprised.
