### ISSUE TITLE
Could you please add the ability to specify the folder...

### ISSUE THREAD

**Issue by xaozai** [seansfkelley/synology-download-manager#11]
Could you please add the ability to specify the folder for saving files (when adding a task)?
Thank you! The extension is very good.

**Comment by seansfkelley** [comment]
Thanks! Glad you like it. I just finished implementing this feature today (as of cd57a9dfefd5774ea89498dcf20d68005bffb15a), so expect to see it in the extension in the coming days after I submit it and it gets approval.

**Comment by seansfkelley** [comment]
This has (finally!) been released.
