### ISSUE TITLE
Unexpected error trying to download file through synology

### ISSUE THREAD

**Issue by axelitus** [seansfkelley/synology-download-manager#125]
### Versions

**Extension version**: 0.6.1

**Browser and version**: Firefox Developer Edition 70.0b12 (64-bit)

**DSM version**: DSM 6.2.2-24922 Update 3

**Download Station version**: 3.8.14-3543

### Failure Logs

```
Redacted extension state: {
  "settings": {
    "connection": {
      "protocol": "https",
      "hostname": true,
      "port": true,
      "username": true,
      "password": true
    },
    "visibleTasks": {
      "downloading": true,
      "uploading": true,
      "completed": true,
      "errored": true,
      "other": true
    },
    "taskSortType": "name-asc",
    "notifications": {
      "enableFeedbackNotifications": true,
      "enableCompletionNotifications": false,
      "completionPollingInterval": 60
    },
    "shouldHandleDownloadLinks": true,
    "badgeDisplayType": "total"
  },
  "tasks": 0,
  "taskFetchFailureReason": null,
  "tasksLastInitiatedFetchTimestamp": 1570549399558,
  "tasksLastCompletedFetchTimestamp": 1570549401132,
  "lastSevereError": "(omitted for brevity)",
  "stateVersion": 5
}

error while trying to fetch metadata file type for download url

Error: 'Request failed with status code 400'
Error stack trace: parcelRequire<["3bIi"]</module.exports@moz-extension://48b9f909-2136-4b43-8162-9616e639fc2f/dist/background/index.js:206:87
parcelRequire<.aS8y</module.exports@moz-extension://48b9f909-2136-4b43-8162-9616e639fc2f/dist/background/index.js:208:129
parcelRequire<.KRuG</module.exports/</p.onreadystatechange@moz-extension://48b9f909-2136-4b43-8162-9616e639fc2f/dist/background/index.js:216:901
```

### Steps to Reproduce the Issue

1. Visit: https://tailwindcss.com/course/styling-the-basic-dropdown-elements
2. Left click the "Download HD" link on the bottom of the video
3. Select Download with DownloadStation

The download is not started and an unexpected error notification is displayed.

The link to the video download is: https://player.vimeo.com/external/363127818.hd.mp4?s=5a02991f9f7fa16d0445e64d5be96022fa326bb5&profile_id=175&download=1

**Comment by seansfkelley** [comment]
Thank you for the detailed bug report! Made this very easy to track down. Now fixed in the latest version (0.6.2).

**Comment by axelitus** [comment]
Excellent! I'll give this a go once the extension gets updated! Thanks for the great response!

**Comment by axelitus** [comment]
I can confirm this is working now on the new version! Thanks!
