### ISSUE TITLE
Unknown error, when adding a link with multiple , and . (i think)

### ISSUE THREAD

**Issue by petersteger** [seansfkelley/synology-download-manager#126]
### Versions
Version 0.6.2, Firefox 69.0.3 64bit
DSM: 6.2.2-24922 U3

Download Station 3.8.14-3543

Sample: ed2k://|file|This.or.that.Matt.,Kenneth,.none.temp,.Kane.HDTV-FTP.avi|576030720|2796D477DDDAED03082710A36CEFF79C|h=4F7WKNFBQQP4Q3QHQUEFSDVEQVK4HVIG|/
This is NOT a valid link, but similar.

**Comment by seansfkelley** [comment]
See also #118.

**Comment by seansfkelley** [comment]
Fixed and released in 0.6.3. Thank you for the bug report!

**Comment by petersteger** [comment]
I very well appreciate your plugin...and my life has been much easier with your plugin ;)
many thanks
