### ISSUE TITLE
Cannot add a download if the site does not support the HEAD request

### ISSUE THREAD

**Issue by sverlan** [seansfkelley/synology-download-manager#127]
When adding a torrent from a site that does not support the HEAD request (the site is answering 501 code) an error is triggered and the download is not added. 

Normally, there is no particular reason to ask for .torrent file metadata. Adding it directly to DSM works without any problems.

**Comment by seansfkelley** [comment]
This should be fixed in the latest version 0.6.4. Please let me know if it's not!

**Comment by sverlan** [comment]
I don't think that your modification is completely solving this issue as the server is returning "501 Not Implemented" and not "405 Method Not Allowed".

According to Wikipedia both codes could be applicable by the server in the considered case:

> **501 Not Implemented**
>     The server either does not recognize the request method, or it lacks the ability to fulfil the request. Usually this implies future availability (e.g., a new feature of a web-service API)
> 
> **405 Method Not Allowed**
>     A request method is not supported for the requested resource; for example, a GET request on a form that requires data to be presented via POST, or a PUT request on a read-only resource.
