### ISSUE TITLE
[Feature Request] "Clear Finished Tasks" option on far left side?

### ISSUE THREAD

**Issue by Shawzborne** [seansfkelley/synology-download-manager#131]
Hello Sir, 

Can you please add a "Clear Finished Tasks" option on far left side with a trash icon? Same as in the other no longer updated "Synology Download Station Extension" from the other developer? 

Thank-you for keeping this extension updated,

Shawn

**Comment by seansfkelley** [comment]
Lucky for you, there already is a clear button in the filtering menu!

https://github.com/seansfkelley/synology-download-manager/blob/master/screenshots/firefox/filtering.png

This will clear any tasks that are completed and not uploading.
