### ISSUE TITLE
feature request - simple activation/deaktivation of this plugin

### ISSUE THREAD

**Issue by tomturican** [seansfkelley/synology-download-manager#136]
I use this extension with mozilla firefox. This extension makes a lot of sense because it simplifies many things for me and makes them more comfortable. Thank you for that!
Because I rarely use this extension for larger downloads, I have a wish. I miss a function of simply activating or deactivating the plugin with a click of the mouse (this can be done via the plugin management, but is too cumbersome for me). The reason is as follows: Whenever I start firefox with an active plugin, my NAS wakes up, although it would not be necessary at this point ....

alternatively: only establish the connection to the NAS when a download is started.
(this new connection establishment every time the browser was started could also be the reason why my NAS takes so long to go into sleep mode ...)

**Comment by seansfkelley** [comment]
Do you have "notify when downloads complete" enabled in the settings? I just took a look through the code and it doesn't seem like it should attempt to communicate with the NAS when you open the browser unless you have those notifications enabled.

**Comment by tomturican** [comment]
Unfortunately, I am currently at my 2 place of residence to work. On the weekend I will check & test it immediately and give an answer here. Thank you very much.

**Comment by tomturican** [comment]
Hi there,
now i'm back home and could try it out. Unfortunately, switching off the function did nothing. I also switched off everything else that was possible. But it is still the same. When the plugin is active, the NAS wakes up whenever Firefox starts. This does not happen if the plugin is inactive.

**Comment by seansfkelley** [comment]
Aha, upon closer reading, I see why that would be happening.

Note to self:

https://github.com/seansfkelley/synology-download-manager/blob/b37c896b21f6e80efe7886b1a94cca09d062c927/src/background/index.ts#L81-L85

The above code runs once when the addon is initialized because the API client settings start empty and need to be filled in from the user-provided settings.

I think it would make sense to always `clearCachedTasks`, but to skip `pollTasks` the first time the callback runs. If the user has configured notifications, it'll still run in the background eventually (or when they open the popup).

**Comment by tomturican** [comment]
I think your plugin works very well as it is. To do this, it always has to communicate with the NAS. I only know a little bit about Arduino programming. So I can't understand your code right away. The notification functions always require a connection to the NAS. And these functions are very useful, so switching them off is not the right way.
The real problem is that Firefox doesn't show inactive plugins in the icon bar. In order to activate an inactive plugin, a detour via the plugin management is always necessary. Otherwise it could be very easy to turn a plugin on or off. I meant that with my wish. It should always be displayed, but offer the possibility to activate or deactivate it.

**Comment by seansfkelley** [comment]
If the problem is only that it wakes the NAS when Firefox starts, then my proposed solution should work: with that change, it will not wake the NAS unless you open the popup, test the connection or enable background updates. This should amount to "disabling" the addon, more or less.

**Comment by tomturican** [comment]
That sounds good. That would mean the NAS won't wake up unless you do anything with the plugin. What is meant by "background tasks". Is this the option that the plugin checks for completed downloads every 60s?

**Comment by seansfkelley** [comment]
Yes, to both.

**Comment by tomturican** [comment]
Yes, that would be the solution. I would be happy to test it soon.
