### ISSUE TITLE
Not attempting to connect with a non-standard port number

### ISSUE THREAD

**Issue by jmapoz** [seansfkelley/synology-download-manager#138]
### Versions

**Extension version**: (visible in Synology Download Manager's settings (Firefox) or in the extension list (Chrome))
0.6.4
**Browser and version**: (usually found in the browser's "About")
Mac Firefox 73.0.1 (64-bit)
**DSM version**: (DSM > Control Panel > Info Center > General > DSM version)
DSM 6.2.2-24922 Update 4
**Download Station version**: (DSM > Package Center > Installed > Download Station > Installed version)
3.8.14-3543

### Steps to Reproduce the Issue

Failing connection and no logs found.  When I use the NAS credentials with the default port number, the add-on appears to try to reach the NAS.  I have a custom port number and when I use that in the add-on, it doesn't appear to correctly attempt a connection and says connection failure

**Comment by seansfkelley** [comment]
Some questions to help debug:

- What do you mean by it "appears to try to reach the NAS"? Does it just have the spinner and never actually connects? Does it ever error?
- What is the exact error message you get when it fails to connect? How quickly does it fail?

**Comment by jmapoz** [comment]
Answers in line

I trust this helps debug, but let me know if you need further information


On 28 February 2020 at 12:07:24 AM, Sean Kelley (notifications@github.com) wrote:

Some questions to help debug:

What do you mean by it "appears to try to reach the NAS"? Does it just have the spinner and never actually connects? Does it ever error?
When I try to connect on port 5001, and click “Test Connection and Save”, it spins saying “Testing connection” for about a minute or so and returns with the message “Connection failure (timeout, check your hostname/port settings and internet connection).”  This would be the correct as the port number is wrong as I use a custom port.  When I try with the correct port, and click “Test Connection and Save”, it immediately comes back with the cross and "Connection failure" as above and never shows the "Testing connection” message


What is the exact error message you get when it fails to connect? How quickly does it fail?
“Connection failure (timeout, check your hostname/port settings and internet connection).”

Immediately

**Comment by seansfkelley** [comment]
I just tried to reproduce this with my NAS by switching the HTTPS port it uses, and was unable to.

> What is the exact error message you get when it fails to connect? How quickly does it fail?
>“Connection failure (timeout, check your hostname/port settings and internet connection).”
>
>Immediately

Are you sure that it's the same message as the previous case? There are a few "connection failure" messages with different explanations. When I was trying to reproduce the issue, I would get 

> Connection failure (likely wrong hostname/port, no internet connection or invalid certificate).

Which is both correct and makes sense to appear immediately. Based on the way timeouts are handled, I would be very surprised if the error message claiming it was a timeout would appear immediately.

**Comment by jmapoz** [comment]
Hi Sean,

Sorry, my mistake, I have rechecked and the messages are different
5001
Connection failure (timeout; check your hostname/port settings and internet connection)
Timeout takes about 60 seconds
Custom port as used to connect to NAS through browser
Connection failure (likely wrong hostname/port, no internet connection or invalid certificate)
I use the default certificate, but the port number is what I use to browser to the NAS.
Timeout immediate
Screen captures attached for your reference, which I hope will get through to you.

- JP 

On 1 March 2020 at 4:01:40 AM, Sean Kelley (notifications@github.com) wrote:

I just tried to reproduce this with my NAS by switching the HTTPS port it uses, and was unable to.

What is the exact error message you get when it fails to connect? How quickly does it fail?
“Connection failure (timeout, check your hostname/port settings and internet connection).”

Immediately

Are you sure that it's the same message as the previous case? There are a few "connection failure" messages with different explanations. When I was trying to reproduce the issue, I would get

Connection failure (likely wrong hostname/port, no internet connection or invalid certificate).

Which is both correct and makes sense to appear immediately. Based on the way timeouts are handled, I would be very surprised if the error message claiming it was a timeout would appear immediately.

**Comment by seansfkelley** [comment]
Okay, this makes a lot more sense. It sounds like a configuration error rather than a bug. Does your browser accept the certificate for normal browsing?

**Comment by seansfkelley** [comment]
Also, are you using the same host name to connect in the extension as you are to log into DSM in a browser tab?

**Comment by jmapoz** [comment]
Hi Sean,

Great, that has helped me find an issue with the way the certificate was saved.  I have removed it and re-accepted it and things are working now.   Thanks for your help.

- JP

On 1 March 2020 at 12:46:20 PM, Sean Kelley (notifications@github.com) wrote:

Okay, this makes a lot more sense. It sounds like a configuration error rather than a bug. Does your browser accept the certificate for normal browsing?

**Comment by seansfkelley** [comment]
Great, happy it works!
