### ISSUE TITLE
Include hint for user on how to fix an error

### ISSUE THREAD

**Issue by SteadyQuad** [seansfkelley/synology-download-manager#139]
I've spent some time hunting down the cause of an error I kept getting when trying to add a (magnet) download URL via right-click link->Download with Download station. The error said "No dafault destination". 

I searched the addon's preferences to set a default destination, only to find out that the cause was within Download Station. For the Synology user I specified in the extension's preferences, there was not default destination set within Download Station. So the solution was to log in to DSM with this user, start Download Station, and set a default directory for downloads there.

Maybe a more descriptive error message might save someone else some time: 

In synology-download-manager/_locales/en/messages.json: 

```
...
  "No_default_destination": {
    "message": "No default destination is set in Download Station for this Synology user.",
    "description": "Error message on Synology API call failure."
  },
...
```

**Comment by seansfkelley** [comment]
Thank you for the suggestion, and sorry for the confusion! I took your phrasing verbatim. You should see it in the next release.
