### ISSUE TITLE
[Feature request] MS Edge compatibility

### ISSUE THREAD

**Issue by TheWyvern13** [seansfkelley/synology-download-manager#142]
Thank you!!!

**Comment by seansfkelley** [comment]
I took a look into this and it appears that Edge [supports installing from the Chrome web store](https://support.microsoft.com/en-us/help/4538971/microsoft-edge-add-or-remove-extensions?ocid=EdgeUI-AddExtension). I did a quick spot-check and it appears to work, so I suggest you try that out!

**Comment by TheWyvern13** [comment]
Dear Sean, it works! Thank you!!!
Giuseppe
