### ISSUE TITLE
Synology Download Manager for Chrome is unable to connect to DSM after the latest Update "DSM 6.2.3-25426" 

### ISSUE THREAD

**Issue by mehedym** [seansfkelley/synology-download-manager#144]
Hi,

Thanks for the amazing extension. I like this very much.
but after the last Synology DSM update " DSM 6.2.3-25426 " this extension is unable to connect to my Synology NAS. 

please let me know when can we expect and update or fix for it ?
error,
https://www.dropbox.com/s/vd0x4sjmxs1wlzs/SDS-Err-01.png?dl=0
dsm version,
https://www.dropbox.com/s/bflycej8rfqs6kt/dsm-update-number.png?dl=0

**Comment by seansfkelley** [comment]
I just checked this on latest Chrome and the latest extension version with my NAS on that same DSM version and it seems to work.

Can you provide [the details mentioned in the issue template](https://github.com/seansfkelley/synology-download-manager/blob/master/.github/ISSUE_TEMPLATE.md) to help me debug?

**Comment by seansfkelley** [comment]
@mehedym do you have any more details on the issue? Browser, OS, etc.? I'm unable to reproduce the issue on macOS using either Chrome or Firefox. My DSM version is the same as yours.

Have you tried removing the extension and reinstalling it?

**Comment by mehedym** [comment]
Hi,

Sorry for the delay in mailing.

after the last DSM update the port 5001 on https was not working.

so i have added a custom port 8001, and then it connected.
I wonder why the default 5001 port, [which was ok before] did not connect ?

[image: image.png]
[image: image.png]

==================================================
| Mehedy Mizan |
| 388/D Free School Street. |
| Hatirpool, Dhanmandi, |
| Dhaka - 1205 |
| Bangladesh |
| Mobile : 01716195822 ((Active)) |
| E-mail : mehedym@gmail.com |
| Web : http://www.ssbdhosting.com |
==================================================

ᐧ

**Comment by seansfkelley** [comment]
Glad you got it working again! After you got it to connect with 8001 did you try to change back to 5001? I'm wondering if you had some transient issue which is resolved now that you're able to connect at all.

Also, I can't see the images you sent in the last post.

[begin cross-post from #147]

This sounds a lot like #147 and, given the timing, I bet it's the same issue. I think the problem and solution here is out of my control; either Firefox or DSM (or both) have conspired to break your configuration, probably by changing something about HTTPS or certificates.
