### ISSUE TITLE
Synology Download Manager for Firefox is unable to connect to DSM after the latest Update 

### ISSUE THREAD

**Issue by Esofasto** [seansfkelley/synology-download-manager#147]
### Description

Synology Download Manager for Firefox is unable to connect to DSM after the latest Update, everything was working fine until Synology DSM update, now the extensions is totally unable to connect to the Synology DS218+ on my local network, DSM version is 6.2.3-25426, firefox is version 77.0.1

### Steps to Reproduce the Issue

Error is consistent, tried to uninstall extension, then reinstall, also tried firefox refresh and deleting all cookies etc

### Failure Logs
https gives error:-

"Connection failed, likely cause: wrong hostname/port, no internet connection or invalid certificate"

http gives error:-
"Connection failed, likely cause: wrong protocol"

Actually I have never been able to connect with https and have always had to use http.

### Versions

**Extension version**: 
0.7.0

**Browser and version**: 
Firefox 77.0.1

**DSM version**: 

6.2.3-25426

**Download Station version**: 3.8.14-3543

**Comment by seansfkelley** [comment]
Thanks for the detailed report! I've seen this issue before and it doesn't look that unusual, but it's concerning that it used to work and now it doesn't.

Regarding HTTPS, do you use a certificate that's untrusted by your browser? I had to visit my NAS in a tab and tell Firefox to accept the certificate before the extension would connect.

Regarding HTTP, it sounds like you may have reused the HTTPS port when trying to connect over HTTP? When it says "wrong protocol" it means it successfully reached the NAS but was rejected by it.

**Comment by Esofasto** [comment]
Sean, I have managed to get your download manager to connect using the certificate trick, however the DLM now gives an error of "Failed to connect to Diskstation Please check your settings"  when clicking a Magnet link (the connection is working in DLM settings), everything was fine a few days ago and as far as I am aware nothing has changed, except a minor update to firefox. I now have to manually paste the torrent link, which kind of defeats the object of the extension!

**Comment by seansfkelley** [comment]
Glad to hear that works again. Having to accept the certificate is expected behavior; the extensions piggyback on the security configuration of the browser but are unable to display the "are you sure" page to allow you to accept the certificate.

I'm not sure what's going on with the magnet link thing. I'll follow up on the other issue you filed, but it sounds like this one is resolved so I'm going to close it out.

[begin cross-post from #144]

This sounds a lot like #144 and, given the timing, I bet it's the same issue. I think the problem and solution here is out of my control; either Firefox or DSM (or both) have conspired to break your configuration, probably by changing something about HTTPS or certificates.

**Comment by auke47** [comment]
I upgraded to DSM 7 but when trying to download a file, I get an error: "Failed to connect to Diskstation. Check your settings."
But when testing the connections in Options, it states: Connection successful!

**Comment by stratusnas** [comment]
For this problem, look the port of your Download Station. The default port for Download Station in https is 8001. Type your host name and port number. For example: https:// host name "conan" and the port number "8001". ex.: https://conan:8001, make exactly that: use the https and type "conan" for host and select or type the port number 8001. If dosn't function you need to change the port of your Download Station, or look on your Synology NAS for the number of the port for Download Station on Login portal -> Aplications.

Before the extension would connect first I had to open my Synology NAS with firefox, in a new tab and tell Firefox to accept the exception for use the certificate instalado en mi Synology NAS.
Regarding for HTTPS connection you need to use a trusted certificate by your browser. Look on let's Encritp. For you Synology NAS have to solicite one certificate on Security -> Certificate -> Add -> Add a new certificate... .
