### ISSUE TITLE
Unable to switch HTTP/HTTPS in connections settings

### ISSUE THREAD

**Issue by kirillkushpel** [seansfkelley/synology-download-manager#150]
### Description

Unable to switch HTTP/HTTPS in connections settings. I've looked through source code, and looks like HTTPS is hardcoded in the `state` component?

https://github.com/seansfkelley/synology-download-manager/blob/master/src/common/state/1.ts

### Steps to Reproduce the Issue

1. Open extention settings, HTTPS is set by default
2. Try to switch to HTTP from dropdown list
3. List won't open

### Failure Logs

Not available

### Versions

**Extension version**: 0.7.0

**Browser version**: Firefox Dev Edition 78.0b8 (64-bit) @Linux Mint 19.3

**DSM version**: DSM 6.2.3-25426

**Comment by seansfkelley** [comment]
Hm, I am unable to reproduce this on my mac running Firefox 77 and 79. I'm surprised this is an issue at all -- the dropdown element isn't doing anything fancy and I haven't changed it meaningfully in months or years. Do the other form elements look disabled? When a connection test is running it does disable the inputs, so I wonder if it got into a weird state there somehow.

**Comment by kirillkushpel** [comment]
It worked one day, then broke) It's a really weird bug, i agree. The thing is that if you use something like ddns, it rarely has HTTPS, and you just can't connect to DSM. Anyway, thanks for the reply :)

**Comment by seansfkelley** [comment]
For sure, and thanks for the report. Are you able to connect over HTTP now, then?
