### ISSUE TITLE
Safari extension

### ISSUE THREAD

**Issue by dxcore35** [seansfkelley/synology-download-manager#156]
Please try to build it as new safari extension.

https://developer.apple.com/safari/extensions/
https://developer.apple.com/documentation/safariservices/safari_app_extensions/building_a_safari_app_extension

**Comment by seansfkelley** [comment]
It appears that publishing Safari extensions require one to be a member of the Apple Developer Program, which I am not and don't intend to pay for. However, you are welcome to package it up yourself an use it on your local Safari installation (for free!) according to the instructions on your linked page.
