### ISSUE TITLE
google takeout

### ISSUE THREAD

**Issue by gosugimoto** [seansfkelley/synology-download-manager#157]
Is there any method to getting google takeout links to work?  I try copying the links from download manager in chrome, and that doesn't seem to work either...

**Comment by seansfkelley** [comment]
Looks like it takes a few days for Google to collect all the data for Takeout, so I can take a look at this in a few days' time. Wild guess: the download requires you to be logged in, but Download Station doesn't have it.

**Comment by seansfkelley** [comment]
I finally found some time to get around to this, and unfortunately, it out's of my control. It appears that the way the Takeout site works is by running some javascript to programmatically trigger a download, meaning that there's no method for the extension to figure out what URL it should send to the NAS.

As a workaround, you could initiate a download in your browser, cancel it, then open the downloads list and pull the URL from there. This also may not work if Google requires login cookies to authenticate the request. Also note that Takeout limits the number of times any given export can be downloaded to just a few, which is obnoxious.
