### ISSUE TITLE
Remove affiliation tag

### ISSUE THREAD

**Issue by T1nd4** [seansfkelley/synology-download-manager#158]
Hi ,
Could you add a checkbox in option to remove affiliation tag when link is interpreted ?
Exemple : 1fichier.com links can have a parameter in link : <link>&af=12345

Actuality, all my links downloaded on 1fichiers are named with the link name, not with the file name. 
Maybe there is a rapport.

**Comment by seansfkelley** [comment]
>  Could you add a checkbox in option to remove affiliation tag when link is interpreted ?

Unfortunately no, as I don't want to have to maintain a list of special cases for every site anyone might be using. I also expect that a general solution is likely to break unrelated sites or require needlessly complex configuration on the part of users.

As a workaround, I suggest that you copy the link as text, adjust it to your liking, and then use the + button in the popup to add the download with your fixed link.

> Actuality, all my links downloaded on 1fichiers are named with the link name, not with the file name.

If you're referring to the name that appears in the list and on disk, that's out of my control. Download Station is the one that decides what to call the download. If you're referring to the name that appears in the popup notification, that's some code I wrote to make a guess based on the URL, but you can safely ignore it as it's only ever used for the notification and not the actual downloaded file.
