### ISSUE TITLE
Private trackers supported?

### ISSUE THREAD

**Issue by s0K0le** [seansfkelley/synology-download-manager#160]
I would like to ask if the extensions support links from a private torrent server like:

`https://domain.com/downloadssl.php?id=111111&torr=filename.torrent`

I tried to add a link as above, but Download Station only downloads the downloadssl.php file (not all the content from the torrent file).

So I think the extension should try to detect if the download URL points to a .torrent or .nzb file. If so, it will download the file in the browser and send it to Download Station on NAS.

[Using DSM 7.0 beta]

**Comment by seansfkelley** [comment]
The extension already attempts to do this, but not all sites behave compatibly. Please see https://github.com/seansfkelley/synology-download-manager/issues/146#issuecomment-640121594 for some more detail. In particular, I suggest you ask the administrators of the private server if it responds to HEAD requests properly.

If you can demonstrate that it's actually the extension at fault here, I can reopen and investigate.
