### ISSUE TITLE
adding one button on the first screen to clear logs

### ISSUE THREAD

**Issue by thomasd3** [seansfkelley/synology-download-manager#161]
When you click on the icon and see the download tasks, it would be nice at the bottom to have a button to clear the downloads which are finished.
Right now we need to click on the funnel account in order to clear the tasks.

**Comment by seansfkelley** [comment]
I made this change mostly in f23e4edee12e0d5802818e91e13ee3d584c0ae13 (as well as a couple commits before/after). Look for it in the next release!
