### ISSUE TITLE
https://sourceforge.net

### ISSUE THREAD

**Issue by tomaasz** [seansfkelley/synology-download-manager#171]
it doesn't grab downloads from https://sourceforge.net

**Comment by seansfkelley** [comment]
In what way does it not work? Can you provide a specific link that fails?

**Comment by tomaasz** [comment]
Please try to download any file from this folder: https://sourceforge.net/projects/nikgapps/files/Releases/NikGapps-R/30-Jan-2021/

**Comment by tomaasz** [comment]
it is not error, it is not possible to add

**Comment by tomaasz** [comment]
jDownloader can download well, you can add there folder or file link

**Comment by tomaasz** [comment]
![image](https://user-images.githubusercontent.com/3982973/106953924-4f845e00-6733-11eb-85ed-1d914628b40f.png)

**Comment by seansfkelley** [comment]
I just gave this a try, and it looks like SourceForge triggers the downloads dynamically with JavaScript. You can read more about that here: https://github.com/seansfkelley/synology-download-manager/blob/master/FAQ.md#why-cant-i-start-a-download-from-a-site-or-how-do-i-start-a-download-with-a-site

As a workaround, you can click "Problems Downloading?" and then in the popup there is a direct link that appears to be work fine with the extension.
