### ISSUE TITLE
private sites download

### ISSUE THREAD

**Issue by gpopesc** [seansfkelley/synology-download-manager#172]
The extension works great for all site, except the private sites (with username and password)

The browser has access to file (.torrent) and it can be downloaded.  It might be possible to have an option automatically upload the file to synology or to load the file in extension from menu? For all this kind of files I need to use synology webui and load the files manually.

Thank you

**Comment by seansfkelley** [comment]
The extension should already do this.

Are you on DSM 7? #166 is tracking an issue where Synology appears to have broken the .torrent upload feature.

Does it work on other private trackers? If so, it's likely that the site in question does not respond to the requests that the extension makes to try to determine if the file is, in fact, a .torrent (as [noted in the FAQ](https://github.com/seansfkelley/synology-download-manager/blob/master/FAQ.md#why-cant-i-start-a-download-from-a-site-or-how-do-i-start-a-download-with-a-site)).

**Comment by gpopesc** [comment]
Thank you for you answer.
I am on DSM 6.2.
Yes, indeed the link is for a php, then it triggers the torrent.
 _https://server.com/download.php?id=718869_
When I right click the link, then download with extension, it shows finished in few seconds and downloads login.php
Maybe you can do something about this.
In chrome I found an extension which can do that, but it is a little bit annoying to change the browser when I try to download. 

Thank you

**Comment by seansfkelley** [comment]
> I am on DSM 6.2.

Thanks, just thought I would check.

> When I right click the link, then download with extension, it shows finished in few seconds and downloads login.php

Yeah, I've seen this exact behavior before too.

>  In chrome I found an extension which can do that, but it is a little bit annoying to change the browser when I try to download.

Which extension are you referring to? As far as I know all these extensions do the same thing for links like this, but it's possible I've missed a case.

**Comment by gpopesc** [comment]
> Which extension are you referring to? As far as I know all these extensions do the same thing for links like this, but it's possible I've missed a case.
 this one works perfect for me https://chrome.google.com/webstore/detail/synology-download-station/onhbegdkgonhlokobjefolhpoidcnida

**Comment by seansfkelley** [comment]
Thanks for all your help chasing down this issue. While I wasn't able to find a test case where this issue arose, I did identify a few cases that are possible and were not handled.

I've just released a new version, 0.9.2, to the Firefox addons site. (Chrome takes quite a bit more time.)

Can you update to 0.9.2 and let me know if your issue is fixed?

**Comment by gpopesc** [comment]
Great ! Congrats! Now it is working fine.

**Comment by seansfkelley** [comment]
Great, thank you for confirming.
