### ISSUE TITLE
MS Edge - Clicking 'Add download...' fails to load folder directory from NAS

### ISSUE THREAD

**Issue by MardukNT** [seansfkelley/synology-download-manager#174]
Adding a torrent via "Add download..." (aka the Plus button) in Synology Download Manager (SDM), fails to load the directory tree from the NAS, when using Chrome extension in MS Edge.

A brief description of the issue:
I've used your extension previously with Firefox browser and it works as expected there. But, when I attempt to add a torrent or magnetic link when using MS Edge, it fails to show the download folders on the NAS. 
Adding a torrent or magnetic link and Clicking on "Add" does download a torrent to the default torrent folder on the NAS, but I cannot pick any subfolders, currently. Issue repros in a InPrivate window as well.

### Steps to Reproduce the Issue

1. Install latest MS Edge for Windows and add SDM from the Chrome Web Store (https://ggle.io/3qwk)
2. Configure a working connection to Synology Download Station.
3. Add a new torrent to download by clicking on the Plus button.
4. Observe message of "Loading directories..."appears, but folders never load.
5. For context, first screenshot is from MS Edge showing the error, and second screenshot is from Firefox, showing correct behavior.
![1 SDM-Edge](https://user-images.githubusercontent.com/79539480/108901277-85e52880-75cf-11eb-9343-5ed744756a40.png)
![2 SDM-Firefox](https://user-images.githubusercontent.com/79539480/108901281-867dbf00-75cf-11eb-9acd-c29341982eed.png)

### Failure Logs

```
No failure logs to attach, but happy to create some, if you can instruct me in their creation.
```

### Versions

**OS**: Windows 10 Pro (20H2 - Build 19042.804)

**Extension version**: Version 0.9.2 (Chrome), Version 0.9.1 (Firefox)

**Browser version**: MS Edge Version 88.0.705.74 (Official build) (64-bit), Firefox 86.0 (64-bit)

**DSM version**: DSM 6.2.3-25426 Update 3

**Download Station version**: 3.8.15-3563

**Comment by MardukNT** [comment]
Edited to fix a typo.

**Comment by seansfkelley** [comment]
Thank you for the detailed bug report!

I have a new release, 0.9.3, pending review that fixes this issue. It usually takes a couple days for the Chrome web store to approve new releases, so look for it soon!

**Comment by MardukNT** [comment]
Sean,
I thank you for all your hard work in squashing bugs, and for making this useful/handy/wonderful web extension in the first place. I look forward to trying out Synology Download Manager **v0.9.3** soon.

--Cheers!

**Comment by MardukNT** [comment]
Sean,
Just leaving a note to say **Download Manager v0.9.3** is working as it should in my environment.
Thank you again for fixing this issue!
