### ISSUE TITLE
Since 0.10 version, can't connect with a "The required method doesn't exist" message

### ISSUE THREAD

**Issue by Maudissure** [seansfkelley/synology-download-manager#182]
Hi,

Since the last update i get a message "The required method doesn't exist" when SDM try to connect to my synology (DSM 7.0).

**Comment by ikstro** [comment]
I have the same problem.
Back to version 9.3

**Comment by hentsch** [comment]
Hi,
Same here. 9.3 works.
Using https, a custom domain (ie domain.com), and a custom port (not 5001). DSM 7.0-41222
Regards

**Comment by seansfkelley** [comment]
Alright, 0.10.1 should work with DSM 7 now. Synology silently broke the authentication API (again).

It's up for Firefox now. Chrome usually takes a couple days for approval.
