### ISSUE TITLE
Torrent file / starting downloading doesn’t work a while 

### ISSUE THREAD

**Issue by neukrisz** [seansfkelley/synology-download-manager#185]
After the latest update of DSM the right click strating download of a torrent doesn't work.
The symptom is same on different computers too in our family and friends circle too. Used torrent site is ncore.pro
Please fix this issue.
Thanks!

**Comment by RamnoJunior** [comment]
Hi,

DSM 7 with Firefox version 88 this new plugin works for me with the new version 0.10.1 of the plugin with ncore.
Whats the error what you got?

Best,
R Jr.

**Comment by neukrisz** [comment]
DSM 6.2.4-25556
Sinology Download Station 2.2.13
Opera 75.0.3969.243
![DSM_extension0](https://user-images.githubusercontent.com/55241755/116818039-9da9d180-ab69-11eb-82ef-7b6450da4ec7.jpg)
![DSM_extension1](https://user-images.githubusercontent.com/55241755/116818040-9e426800-ab69-11eb-96e1-4a10cc16c9a2.jpg)
![DSM_extension2](https://user-images.githubusercontent.com/55241755/116818041-9e426800-ab69-11eb-93d8-c30772236138.jpg)

**Comment by seansfkelley** [comment]
@neukrisz that's a different extension, but if you'd like to use this one, you can [follow these instructions](https://github.com/seansfkelley/synology-download-manager#browsers-reported-to-work) to install it for Opera. It works with the latest versions of DSM.

**Comment by neukrisz** [comment]
It's WORKING! Thanks for your help! :)
