### ISSUE TITLE
customization of target location

### ISSUE THREAD

**Issue by brainchild0** [seansfkelley/synology-download-manager#187]
Users running the extension on multiple systems may wish for finer control of the download destination, for example, by configuring a separate   subfolder for each client, or in some cases a folder entirely outside of the one designated in Download Station. Does Download Station offer any support that would enable such an enhancement on the client?

**Comment by seansfkelley** [comment]
Yes; if you use the + button (instead of the right-click menu) you can choose a new location for each download. Does that address your usage?

**Comment by brainchild0** [comment]
It helps, but the requested use differs in the two following respects:

1. The target address is acquired directly from the hyperlink, not the text box.
2. The target directory is   persistently configured for the extension instance, in order to organize the top-level structure according to client  (e.g. `laptop/`, `desktop/`, `mobile/`).

**Comment by brainchild0** [comment]
Yes, I am aware of the workaround, but the use is common enough, I would imagine, to deserve serious consideration as a specific feature. 

I added details to   #181, so find no need to keep this topic open. Note that some considerations are more general than the indicated strictly by the current title of  #181. A different one might be considered, to attract interested parties, as well as to help discovery in searches.
