### ISSUE TITLE
does not build on Windows 10

### ISSUE THREAD

**Issue by rockonedege** [seansfkelley/synology-download-manager#19]
while executing `npm run build` , it fails with the following log:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@3.10.10
3 info using node@v6.10.2
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle synology-download-manager@0.1.0~prebuild: synology-download-manager@0.1.0
6 silly lifecycle synology-download-manager@0.1.0~prebuild: no script for prebuild, continuing
7 info lifecycle synology-download-manager@0.1.0~build: synology-download-manager@0.1.0
8 verbose lifecycle synology-download-manager@0.1.0~build: unsafe-perm in lifecycle true
9 verbose lifecycle synology-download-manager@0.1.0~build: PATH: {....}
11 silly lifecycle synology-download-manager@0.1.0~build: Args: [ '/d /s /c',
11 silly lifecycle   '(rm -r lib dist || true) && npm run build:transpile && npm run build:bundle && npm run build:styles' ]
12 silly lifecycle synology-download-manager@0.1.0~build: Returned: code: 1  signal: null
13 info lifecycle synology-download-manager@0.1.0~build: Failed to exec build script
14 verbose stack Error: synology-download-manager@0.1.0 build: `(rm -r lib dist || true) && npm run build:transpile && npm run build:bundle && npm run build:styles`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:886:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid synology-download-manager@0.1.0
16 verbose cwd E:\synology-download-manager
17 error Windows_NT 10.0.16237
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
19 error node v6.10.2
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error synology-download-manager@0.1.0 build: `(rm -r lib dist || true) && npm run build:transpile && npm run build:bundle && npm run build:styles`
22 error Exit status 1
23 error Failed at the synology-download-manager@0.1.0 build script '(rm -r lib dist || true) && npm run build:transpile && npm run build:bundle && npm run build:styles'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the synology-download-manager package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     (rm -r lib dist || true) && npm run build:transpile && npm run build:bundle && npm run build:styles
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs synology-download-manager
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls synology-download-manager
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by rockonedege** [comment]
tried and failed again with ubuntu 16.04 on Windows 10:

> synology-download-manager@0.1.0 build /mnt/e/synology-download-manager
> (rm -r lib dist || true) && npm run build:transpile && npm run build:bundle && npm run build:styles

rm: cannot remove 'lib': No such file or directory
rm: cannot remove 'dist': No such file or directory

> synology-download-manager@0.1.0 build:transpile /mnt/e/synology-download-manager
> tsc


> synology-download-manager@0.1.0 build:bundle /mnt/e/synology-download-manager
> node build.js

building lib/settings/index.js
building lib/background/index.js
building lib/popup/index.js

> synology-download-manager@0.1.0 build:styles /mnt/e/synology-download-manager
> scss --update scss:dist/css

sh: 1: scss: not found

npm ERR! Linux 4.4.0-43-Microsoft
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build:styles"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! synology-download-manager@0.1.0 build:styles: `scss --update scss:dist/css`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the synology-download-manager@0.1.0 build:styles script 'scss --update scss:dist/css'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the synology-download-manager package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     scss --update scss:dist/css
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs synology-download-manager
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls synology-download-manager
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /mnt/e/synology-download-manager/npm-debug.log

npm ERR! Linux 4.4.0-43-Microsoft
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! synology-download-manager@0.1.0 build: `(rm -r lib dist || true) && npm run build:transpile && npm run build:bundle && npm run build:styles`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the synology-download-manager@0.1.0 build script '(rm -r lib dist || true) && npm run build:transpile && npm run build:bundle && npm run build:styles'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the synology-download-manager package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     (rm -r lib dist || true) && npm run build:transpile && npm run build:bundle && npm run build:styles
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs synology-download-manager
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls synology-download-manager
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /mnt/e/synology-download-manager/npm-debug.log

**Comment by seansfkelley** [comment]
Oops, rookie mistakes on my part. :) Not sure what's failing the first but 1290408ed762e1ee8fbe79a23e83b75663ad62f1 replaces `rm` with `rimraf` which should work cross-platform and be less noisy and 635eff53d159a8b0b64048b9cdb5adeef1dc01da should stop accidentally referring to a global `scss` executable and instead use `node-sass` (which was the second issue).

**Comment by rockonedege** [comment]
This fixed `npm run build` for Windows 10 native, but failed again in the WSL(ubuntu 16.04) , see log below:

/mnt/e/synology-download-manager$ npm run build

> synology-download-manager@0.1.0 build /mnt/e/synology-download-manager
> rimraf lib dist && npm run build:transpile && npm run build:bundle && npm run build:styles


> synology-download-manager@0.1.0 build:transpile /mnt/e/synology-download-manager
> tsc


> synology-download-manager@0.1.0 build:bundle /mnt/e/synology-download-manager
> node build.js

building lib/settings/index.js
building lib/background/index.js
building lib/popup/index.js

> synology-download-manager@0.1.0 build:styles /mnt/e/synology-download-manager
> node-sass --recursive --output dist/css scss

/mnt/e/synology-download-manager/node_modules/node-sass/lib/binding.js:15
      throw new Error(errors.missingBinary());
      ^

Error: Missing binding /mnt/e/synology-download-manager/node_modules/node-sass/vendor/linux-x64-48/binding.node
Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 6.x

Found bindings for the following environments:
  - Windows 64-bit with Node.js 6.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass --force` to build the binding for your current environment.
    at module.exports (/mnt/e/synology-download-manager/node_modules/node-sass/lib/binding.js:15:13)
    at Object.<anonymous> (/mnt/e/synology-download-manager/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/mnt/e/synology-download-manager/node_modules/node-sass/bin/node-sass:11:10)

npm ERR! Linux 4.4.0-43-Microsoft
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build:styles"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! synology-download-manager@0.1.0 build:styles: `node-sass --recursive --output dist/css scss`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the synology-download-manager@0.1.0 build:styles script 'node-sass --recursive --output dist/css scss'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the synology-download-manager package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-sass --recursive --output dist/css scss
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs synology-download-manager
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls synology-download-manager
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /mnt/e/synology-download-manager/npm-debug.log

npm ERR! Linux 4.4.0-43-Microsoft
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! synology-download-manager@0.1.0 build: `rimraf lib dist && npm run build:transpile && npm run build:bundle && npm run build:styles`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the synology-download-manager@0.1.0 build script 'rimraf lib dist && npm run build:transpile && npm run build:bundle && npm run build:styles'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the synology-download-manager package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rimraf lib dist && npm run build:transpile && npm run build:bundle && npm run build:styles
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs synology-download-manager
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls synology-download-manager
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /mnt/e/synology-download-manager/npm-debug.log

**Comment by seansfkelley** [comment]
Did you try doing what the error message says?

```
Error: Missing binding /mnt/e/synology-download-manager/node_modules/node-sass/vendor/linux-x64-48/binding.node
Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 6.x

Found bindings for the following environments:
  - Windows 64-bit with Node.js 6.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass --force` to build the binding for your current environment.
```

**Comment by rockonedege** [comment]
yes, no help though.  I figure it might be I am using the same copy both from Windows and WSL  Ubuntu. 
I cloned another copy  specifically for ubuntu, and it works happily for both. Thanks for the quick fixes.
