### ISSUE TITLE
missing zip on windows 10

### ISSUE THREAD

**Issue by rockonedege** [seansfkelley/synology-download-manager#20]
see log below

E:\synology-download-manager> npm run zip

> synology-download-manager@0.1.0 zip E:\synology-download-manager
> rimraf addon.zip && zip -r addon.zip . -i 'dist/*' -i 'html/*' -i 'icons/*' -i 'vendor/*' -i 'manifest.json' -x '**/*.map' -x '**/.DS_Store'

'zip' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 10.0.16237
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "zip"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! synology-download-manager@0.1.0 zip: `rimraf addon.zip && zip -r addon.zip . -i 'dist/*' -i 'html/*' -i 'icons/*' -i 'vendor/*' -i 'manifest.json' -x '**/*.map' -x '**/.DS_Store'`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the synology-download-manager@0.1.0 zip script 'rimraf addon.zip && zip -r addon.zip . -i 'dist/*' -i 'html/*' -i 'icons/*' -i 'vendor/*' -i 'manifest.json' -x '**/*.map' -x '**/.DS_Store''.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the synology-download-manager package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rimraf addon.zip && zip -r addon.zip . -i 'dist/*' -i 'html/*' -i 'icons/*' -i 'vendor/*' -i 'manifest.json' -x '**/*.map' -x '**/.DS_Store'
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs synology-download-manager
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls synology-download-manager
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\synology-download-manager\npm-debug.log

**Comment by seansfkelley** [comment]
Changed to use `node-zip` rather than native zip.

**Comment by rockonedege** [comment]
works like a charm.
