### ISSUE TITLE
Add-on stopped working after latest Download Station update

### ISSUE THREAD

**Issue by cypresstwist** [seansfkelley/synology-download-manager#22]
![menu_208](https://user-images.githubusercontent.com/14321154/28865144-8cfb1170-7777-11e7-99d9-118f0dfec959.png)
I love this add-on. I use it with the latest Firefox. The add-on stopped working yesterday after I updated Download Station on my Synology NAS (DS115J). Just wanted to give you a heads up.

**Comment by cypresstwist** [comment]
Now it's working again, an hour later. Must have updated it. Thank you.

**Comment by seansfkelley** [comment]
Mysterious! Glad it worked itself out, and thanks for the feedback/letting me know. In the future, you can also hover on "error loading tasks" to get a tooltip explaining what the error was, which may be something easy to correct right away.
