### ISSUE TITLE
add "delete all completed tasks" button

### ISSUE THREAD

**Issue by mgg1959** [seansfkelley/synology-download-manager#25]
Hi, now we can only delete one download every time, must be a way of delete all on any place in the menu
http://prntscr.com/g40xq
http://prntscr.com/g40xv8
Thanks a lot

**Comment by seansfkelley** [comment]
Perhaps the right solution here is a mass-edit mode with (de)select-all and checkboxes.

For the time being, you don't have to wait for a deletion to complete to try to delete other things, so you can go wild clicking the X on all your tasks.

**Comment by mgg1959** [comment]
Hi, that's true, a select all downloads will be great, in my case the
problem is that I usually don't delete the tasks, and now I got nearly 100
to delete.
Thanks for your reply, good luck

Marcel Garcia

El dia 4 ag. 2017 04:48, "Sean Kelley" <notifications@github.com> va
escriure:

**Comment by seansfkelley** [comment]
If you just don't want to see the tasks and don't mind leaving the inactive ones lying around Download Station, you can also open the settings and hide "completed, not uploading" tasks from the view.

**Comment by mgg1959** [comment]
Thanks a lot seansfkelley, i was forget that option.

**Comment by noplanman** [comment]
Awesome, thanks @seansfkelley, was waiting eagerly for this one 😇
