### ISSUE TITLE
Allow adding multiple URLs at once

### ISSUE THREAD

**Issue by seansfkelley** [seansfkelley/synology-download-manager#28]

**Comment by noplanman** [comment]
@seansfkelley Any progress on this?
Should be quite straight-forward to implement, no?

**Comment by seansfkelley** [comment]
No progress; I only get time to work on this project sporadically. If you'd like to open a PR for it though I'd be happy to take a look.

**Comment by seansfkelley** [comment]
This might be as simple as splitting on newlines -- though for good UX, the feedback should mention how many things it's attempting to add (in the notification and in the dropdown, but hopefully also in the right-click menu?).
