### ISSUE TITLE
Log in with different cookie than normal browser user?

### ISSUE THREAD

**Issue by elisimpson** [seansfkelley/synology-download-manager#32]
If the extension is logging into a different user than normally used for your browser DSM sessions, the extension always highjacks the cookie so have to log out of the extension user and back into the normal browser user.

Example:
- normally log into DSM with user "my-user" and check "remember me" to save the login in a cookie.
- set extension to log in with user "synology-download-manager"
- go to DSM, user will be "synology-download-manager", have to log out, and log in to "my-user"

**Comment by seansfkelley** [comment]
This is very strange. The extension specifically does not use cookies, but instead holds onto a unique session ID granted by DSM to hand back with requests. I'm not sure by what mechanism it would be leaking across into your normal browsing state, if that's what it's doing.

I followed your three steps above, including removing the extension entirely to start with a blank slate, and I wasn't able to see the behavior on Firefox 56.0.2. What browser version and DSM version are you on? Are you able to get it to happen reliably with the steps outlined above with no other intervening actions?

**Comment by elisimpson** [comment]
I'm playing around with it some more to see if I can get you info to help
diagnose. One thing I found right away: if I'm logged in to DSM as "user1"
and go to the extension options screen and set the user/pass for "user2"
and hit the "test connection" button I'm immediately logged out from
user1's DSM session (goes back to the log in screen). That implies
something in the extension is overriding the browser's normal session.

As far as versions go:
FF: 56.0.2
DSM: 6.1 with latest patch
Synology Download Manger ext: 0.2.1

**Comment by seansfkelley** [comment]
Alright, I got a repro working, but unsure how minimal it is. Steps:

1. Disable all my addons and remove Synology Download Manager.
2. Restart Firefox to ensure a clean slate w/r/t the addons.
3. In Firefox's preferences, always allow third-party cookies (no idea if this would make a difference, but it's caused weird problems around sessions for me in the past).
4. Log into DSM using the external URL I have setup through Synology (i.e., `example.synology.me`) with some user A.
5. Close the tab I'm logged into DSM with.
6. Install the Synology Download Manager addon.
7. Set up the addon with some user B (who has fewer permissions than user A, fwiw).
8. Hit "Test Connection".
9. Open DSM again in a new tab.

Now I'm logged out. Weird.

**Comment by seansfkelley** [comment]
The above repro still works (i.e. breaks) with the latest version on master too. If I [drop the part of the login test where it logs outs after itself](https://github.com/seansfkelley/synology-download-manager/blob/0a069cf8d1a02ef901c6281f0ba3e57f9d1a1df1/src/settings/settingsUtils.ts#L46), it just ends up hijacking the session, but leaving it logged in.

**Comment by seansfkelley** [comment]
This is also happening with SynoLoader and SynoNext (other Firefox extensions). Synology Download Extender and SynoExt just didn't work on my install. 

Given that this only started happening recently and affects all functioning addons, I'm going to guess that either Mozilla or Synology introduced a bug in a recent version that is allowing sessions to leak across boundaries. Synology seems more likely, since this addon doesn't use cookies, so the NAS might be doing something weird that's causing it to confuse sessions originating from the same browser (sessions don't appear to leak across browsers, at least).

**Comment by seansfkelley** [comment]
Should be fixed on master using undocumented APIs (spooky!). Look for the release in the coming days.

**Comment by elisimpson** [comment]
Tried the update today and it seems to have fixed the issue... Thanks!

**Comment by seansfkelley** [comment]
Of course!

For my own future reference: this is a known issue that using a higher version of the auth APIs don't have. Those newer versions are not documented, and after asking Synology support where I could find the docs for what changed between API versions and what's current, I got the response (paraphrasing) "i dunno lol" which isn't entirely helpful...
