### ISSUE TITLE
Automatically open magnet links

### ISSUE THREAD

**Issue by baile** [seansfkelley/synology-download-manager#33]
The feature that when you click on a magnet link, Firefox automatically opens it with the extension "Synology Download Manager". 

I have been using this feature in SynoLoader for a time. You set "extensions.SynoLoader.use_magnet; true" in about: config and after that, each magnet you click on opens automatically by the extension, awesome.

I think this code has something to do with that:
https://github.com/Lemutar/Synoloader/blob/master/src/modules/MagnetHandler.js

**Comment by seansfkelley** [comment]
Related, possibly a subset of #13. I'll check it out!

**Comment by seansfkelley** [comment]
Added in 99a86637ed8077d0decdc47909598fbbb29b5fa6; should make it into the next release.
