### ISSUE TITLE
Consider adding seeding progress?

### ISSUE THREAD

**Issue by bobmaerten** [seansfkelley/synology-download-manager#58]
Hi, and thanks for this great extension. Coming from Chrome with a [similar product](https://www.download-station-extension.com), I find very smart to display remaining seeding ratio for bittorent downloads like on the screeshot :

![](https://cl.ly/2h381t1j212B/Image%202017-12-20%20at%2010.42.45%20AM.png)

Here the blue bar stands for download and the green one for upload completion according to rules set in Download Station configuration.

**Comment by seansfkelley** [comment]
Judging by the source, it looks like that green bar is not sized based on the desired seed ratio set in DSM, but it just a ratio of `uploaded / downloaded`, which seems a bit misleading. Would you still consider that useful? I can't find anywhere in the API that the "automatically stop seeding" options from the UI would be surfaced.

**Comment by bobmaerten** [comment]
Ok, I was fooled by what it seems to be an estimated value. Never mind, be thanks anyway!
