### ISSUE TITLE
Estimated time to finish download each file **feature request**

### ISSUE THREAD

**Issue by simonmb** [seansfkelley/synology-download-manager#60]
Would it be possible to show the estimated time to download each file?

**Comment by seansfkelley** [comment]
Hm, it doesn't look like the DownloadStation API gives out an estimated time, so we'd have to compute it ourselves and be subject to the wildly swinging estimates as the download speed changes. Still, seems like a useful thing to have, so I'll try to include it in the net batch of changes.

**Comment by simonmb** [comment]
Would it be possible to cache the value somehow and average it?

**Comment by seansfkelley** [comment]
Yeah, there's some basic methods to improve the quality of the guess, but it might still end up like the [Windows file copy dialog](https://xkcd.com/612/). :)

**Comment by simonmb** [comment]
This night be interesting;
https://stackoverflow.com/questions/2779600/how-to-estimate-download-time-remaining-accurately
