### ISSUE TITLE
Firefox error updating tasks (connection failure)

### ISSUE THREAD

**Issue by smolyn** [seansfkelley/synology-download-manager#65]
### Versions
**Extension version**: 0.4.1
**Browser and version**: Firefox Nightly 59.0a1 (2018-01-04) (64-bit)
**DSM version**: DSM 6.1.4-15217 Update 5
**Download Station version**: 3.8.7-3490

### Steps to Reproduce the Issue
1. Configure add on, run "test connection", confirm connection works
2. Addon dropdown shows "Error updating tasks" (hover-over says "Connection failure")
3. Opening the Download Station UI button works fine and logs in directly

**Comment by seansfkelley** [comment]
Those are very strange symptoms. Is there any explanatory text after "connection failure"? Usually there's a phrase after in that parentheses, such as "(likely wrong protocol)".

To be clear, this means there was an issue with the extension even connecting to DSM; it usually means something mundane is wrong (like a typo in the hostname), but if your connection test works that's definitely confusing.

**Comment by smolyn** [comment]
Hmm seems to have resolved itself after I removed it and reinstalled.
