### ISSUE TITLE
Support for private trackers

### ISSUE THREAD

**Issue by khrt** [seansfkelley/synology-download-manager#73]
Add a support for private trackers like it's done in https://www.download-station-extension.com/faq#faq_answer_24

**Comment by seansfkelley** [comment]
This extension actually [does exactly that check](https://github.com/seansfkelley/synology-download-manager/blob/807785133e4595a8351af8d239583a437cc892b6/src/common/apis/actions.ts#L212) described there:

> Technically speaking, the extension is only able to detect torrents or .nzb files if the download URL ends with the correct file extension (.torrent or .nzb) and/or the file is transferred with the Content-Type header "application/x-bittorrent" or "application/x-nzb". 

Are you able to check if that extension works for your site while this one doesn't? I would expect them to succeed and fail for the same sites.

**Comment by khrt** [comment]
I've double checked that and yours doesn't behave that way as the others.

The other actually download a file by a browser and then add a task to download station, when yours just adds a task to download a torrent file.
