### ISSUE TITLE
"Unknown error displaying tasks"

### ISSUE THREAD

**Issue by aarfing** [seansfkelley/synology-download-manager#78]
### Versions

**Extension version**: 0.5.0

**Browser and version**: Firefox 60.0b7 (same happens in Nightly 61)

**DSM version**: DSM 6.1.5-15254 Update 1

**Download Station version**: 3.8.7-3490

### Steps to Reproduce the Issue

1. Launch Firefox
2. Click on the "Synology Download Manager"-icon in the toolbar
3. "Synology Download Manager"-window says "Unknown error displaying tasks"

### Information from error

Error: 'never assertion failed, got value undefined'
Error stack trace: assertNever@moz-extension://7fac877b-cced-1d49-8469-fdf1c0a01305/dist/js/popup.js:25132:11
sortTasks@moz-extension://7fac877b-cced-1d49-8469-fdf1c0a01305/dist/js/popup.js:29059:20
renderTaskList@moz-extension://7fac877b-cced-1d49-8469-fdf1c0a01305/dist/js/popup.js:30006:114
render@moz-extension://7fac877b-cced-1d49-8469-fdf1c0a01305/dist/js/popup.js:29912:17
finishClassComponent@moz-extension://7fac877b-cced-1d49-8469-fdf1c0a01305/dist/js/popup.js:10727:22
updateClassComponent@moz-extension://7fac877b-cced-1d49-8469-fdf1c0a01305/dist/js/popup.js:10704:12
beginWork@moz-extension://7fac877b-cced-1d49-8469-fdf1c0a01305/dist/js/popup.js:11079:16
performUnitOfWork@moz-extension://7fac877b-cced-1d49-8469-fdf1c0a01305/dist/js/popup.js:13078:16
workLoop@moz-extension://7fac877b-cced-1d49-8469-fdf1c0a01305/dist/js/popup.js:13142:26
callCallback@moz-extension://7fac877b-cced-1d49-8469-fdf1c0a01305/dist/js/popup.js:3396:9
invokeGuardedCallbackDev@moz-extension://7fac877b-cced-1d49-8469-fdf1c0a01305/dist/js/popup.js:3435:7
invokeGuardedCallback@moz-extension://7fac877b-cced-1d49-8469-fdf1c0a01305/dist/js/popup.js:3292:5
renderRoot@moz-extension://7fac877b-cced-1d49-8469-fdf1c0a01305/dist/js/popup.js:13220:7
performWorkOnRoot@moz-extension://7fac877b-cced-1d49-8469-fdf1c0a01305/dist/js/popup.js:13868:24
performWork@moz-extension://7fac877b-cced-1d49-8469-fdf1c0a01305/dist/js/popup.js:13821:7
requestWork@moz-extension://7fac877b-cced-1d49-8469-fdf1c0a01305/dist/js/popup.js:13732:7
scheduleWorkImpl@moz-extension://7fac877b-cced-1d49-8469-fdf1c0a01305/dist/js/popup.js:13586:11
scheduleWork@moz-extension://7fac877b-cced-1d49-8469-fdf1c0a01305/dist/js/popup.js:13543:12
scheduleTopLevelUpdate@moz-extension://7fac877b-cced-1d49-8469-fdf1c0a01305/dist/js/popup.js:14047:5
updateContainer@moz-extension://7fac877b-cced-1d49-8469-fdf1c0a01305/dist/js/popup.js:14085:7
renderSubtreeIntoContainer/<@moz-extension://7fac877b-cced-1d49-8469-fdf1c0a01305/dist/js/popup.js:18080:7
unbatchedUpdates@moz-extension://7fac877b-cced-1d49-8469-fdf1c0a01305/dist/js/popup.js:13956:12
renderSubtreeIntoContainer@moz-extension://7fac877b-cced-1d49-8469-fdf1c0a01305/dist/js/popup.js:18079:5
render@moz-extension://7fac877b-cced-1d49-8469-fdf1c0a01305/dist/js/popup.js:18144:12
@moz-extension://7fac877b-cced-1d49-8469-fdf1c0a01305/dist/js/popup.js:30109:13
fetchStateAndNotify/</<@moz-extension://7fac877b-cced-1d49-8469-fdf1c0a01305/dist/js/popup.js:25653:32
fetchStateAndNotify/<@moz-extension://7fac877b-cced-1d49-8469-fdf1c0a01305/dist/js/popup.js:25653:9

React stack trace:
    in Popup
    in FatalErrorWrapper

**Comment by seansfkelley** [comment]
Hey there, thanks for filing an issue! This helps me diagnose the immediate cause, but unfortunately is not enough information to figure out how the extension got into a bad state. I just pushed a new version (v0.5.1) to the addons store that will include more debugging information. If you don't mind, could you update your version and then try it again and post the debugging information here? Thanks!

**Comment by aarfing** [comment]
Here's the information from 0.5.1:

Redacted extension state: {
  "lastSevereError": "(omitted for brevity)",
  "connection": {
    "protocol": "https",
    "hostname": true,
    "port": true,
    "username": true,
    "password": true
  },
  "visibleTasks": {
    "downloading": true,
    "uploading": false,
    "completed": true,
    "errored": true,
    "other": true
  },
  "notifications": {
    "enableFeedbackNotifications": true,
    "enableCompletionNotifications": false,
    "completionPollingInterval": 60
  },
  "tasks": 4,
  "taskFetchFailureReason": null,
  "tasksLastInitiatedFetchTimestamp": 1522304022778,
  "tasksLastCompletedFetchTimestamp": 1522304023048,
  "stateVersion": 2
}

Error: 'never assertion failed, got value undefined'
Error stack trace: assertNever@moz-extension://7fac877b-cced-1d49-8469-fdf1c0a01305/dist/js/popup.js:25132:11
sortTasks@moz-extension://7fac877b-cced-1d49-8469-fdf1c0a01305/dist/js/popup.js:29123:20
renderTaskList@moz-extension://7fac877b-cced-1d49-8469-fdf1c0a01305/dist/js/popup.js:30072:114
render@moz-extension://7fac877b-cced-1d49-8469-fdf1c0a01305/dist/js/popup.js:29978:17
finishClassComponent@moz-extension://7fac877b-cced-1d49-8469-fdf1c0a01305/dist/js/popup.js:10727:22
updateClassComponent@moz-extension://7fac877b-cced-1d49-8469-fdf1c0a01305/dist/js/popup.js:10704:12
beginWork@moz-extension://7fac877b-cced-1d49-8469-fdf1c0a01305/dist/js/popup.js:11079:16
performUnitOfWork@moz-extension://7fac877b-cced-1d49-8469-fdf1c0a01305/dist/js/popup.js:13078:16
workLoop@moz-extension://7fac877b-cced-1d49-8469-fdf1c0a01305/dist/js/popup.js:13142:26
callCallback@moz-extension://7fac877b-cced-1d49-8469-fdf1c0a01305/dist/js/popup.js:3396:9
invokeGuardedCallbackDev@moz-extension://7fac877b-cced-1d49-8469-fdf1c0a01305/dist/js/popup.js:3435:7
invokeGuardedCallback@moz-extension://7fac877b-cced-1d49-8469-fdf1c0a01305/dist/js/popup.js:3292:5
renderRoot@moz-extension://7fac877b-cced-1d49-8469-fdf1c0a01305/dist/js/popup.js:13220:7
performWorkOnRoot@moz-extension://7fac877b-cced-1d49-8469-fdf1c0a01305/dist/js/popup.js:13868:24
performWork@moz-extension://7fac877b-cced-1d49-8469-fdf1c0a01305/dist/js/popup.js:13821:7
requestWork@moz-extension://7fac877b-cced-1d49-8469-fdf1c0a01305/dist/js/popup.js:13732:7
scheduleWorkImpl@moz-extension://7fac877b-cced-1d49-8469-fdf1c0a01305/dist/js/popup.js:13586:11
scheduleWork@moz-extension://7fac877b-cced-1d49-8469-fdf1c0a01305/dist/js/popup.js:13543:12
scheduleTopLevelUpdate@moz-extension://7fac877b-cced-1d49-8469-fdf1c0a01305/dist/js/popup.js:14047:5
updateContainer@moz-extension://7fac877b-cced-1d49-8469-fdf1c0a01305/dist/js/popup.js:14085:7
renderSubtreeIntoContainer/<@moz-extension://7fac877b-cced-1d49-8469-fdf1c0a01305/dist/js/popup.js:18080:7
unbatchedUpdates@moz-extension://7fac877b-cced-1d49-8469-fdf1c0a01305/dist/js/popup.js:13956:12
renderSubtreeIntoContainer@moz-extension://7fac877b-cced-1d49-8469-fdf1c0a01305/dist/js/popup.js:18079:5
render@moz-extension://7fac877b-cced-1d49-8469-fdf1c0a01305/dist/js/popup.js:18144:12
@moz-extension://7fac877b-cced-1d49-8469-fdf1c0a01305/dist/js/popup.js:30175:13
fetchStateAndNotify/</<@moz-extension://7fac877b-cced-1d49-8469-fdf1c0a01305/dist/js/popup.js:28206:32
fetchStateAndNotify/<@moz-extension://7fac877b-cced-1d49-8469-fdf1c0a01305/dist/js/popup.js:28206:9

React stack trace:
    in Popup
    in FatalErrorWrapper

**Comment by seansfkelley** [comment]
Alright, I think I know what the issue was. I should have time to fix this in the next couple days. If you want to fix it for yourself right now, the only path is to remove the extension and reinstall it (i.e. starting from a blank slate).

For my future self:

Looks like the direct cause is missing the `taskSortType` and `shouldHandleDownloadLinks` options entirely. These were added after the initial version of the state was laid down, but before there was a formal versioning method.

The reason they're missing is likely because the way that new state pieces were introduced: when a listener asked for the state, it would get the defaults merged in, but unless the settings were changed in the settings UI and saved, those defaults were never in turn persisted to the data store. When the new version was released, it assumed that these values were persisted, which is not the case if you never changed your settings after those fields were introduced.

This shouldn't be an issue in the future because the state-version-update process now persists the updated state before handing it off to the rest of the code (but this should be verified).

The best fix is probably to introduce a new state version that doesn't change the shape but specifically re-merges in missing default values to make sure that everything that should be there is. It can also whitelist values so that the `...state` splat doesn't carry along old junk that isn't relevant anymore.

**Comment by seansfkelley** [comment]
I should also do #76 while doing this. A specific test can be added for this transition to ensure that erroneously missing fields are included re-included with the new state version.

**Comment by aarfing** [comment]
Excellent. Thank you. I'll just wait for the fix, so I can help confirm, that the bug is indeed squashed.

**Comment by seansfkelley** [comment]
Thanks! I just submitted 0.5.2 which should be available shortly and includes this fix. Let me know!

**Comment by aarfing** [comment]
That fixed it! Thanks :)
