### ISSUE TITLE
Broken Link Status

### ISSUE THREAD

**Issue by conche1** [seansfkelley/synology-download-manager#82]
I get the Broken Link Status in Download Station when using either Firefox or Safari, but works absolutely fine in Chrome. Have you come across this issue previously?
Thanks :)

**Comment by seansfkelley** [comment]
The Chrome version was accidentally outdated. I just updated both Firefox and Chrome versions to be 0.5.2 (I don't explicitly support Safari -- not sure what you're doing to test it there). Does it still work on Chrome in the newest version? They shouldn't be doing anything differently from each other.

**Comment by conche1** [comment]
Sorry I was using a different extension for Chrome. I have just download Synology Download Manager for Chrome and I am getting the same problem as I was for Firefox (Broken Link). The site I'm trying to fetch data from has a private tracker - not sure if that makes a difference?
Thanks

**Comment by seansfkelley** [comment]
Does this happen with all downloads from this site? What happens if you try to use downloads from another site? What type of download is it (magnet, .torrent file, etc.)?

**Comment by conche1** [comment]
Yes it happens with all downloads from this site. I have tried using different sites as well and get the same issues. These are all torrent files. When i test my connection through preferences, my connection is always successful, so there is no issue there.
Thanks

**Comment by seansfkelley** [comment]
Does the latest version v0.5.5 fix this? It includes a change to the way that .torrent files are loaded to make it work in more cases.

Just to be clear: the task is being added to the list, but it's shown with an error and says "broken link"? Do other types of downloads (like magnet links) work?

**Comment by conche1** [comment]
Thanks for your help but unfortunately it still seems to be an issue. I have tried on other sites and seems to work well so I'm assuming its site specific and a completely different issue. Thank you anyway...appreciate it!

**Comment by seansfkelley** [comment]
Alright, I'm going to close this issue out then. Sorry we couldn't resolve your issue!
