### ISSUE TITLE
No connexion setting fields in preferences and no drop down menu on icon click

### ISSUE THREAD

**Issue by Audren13** [seansfkelley/synology-download-manager#84]
Hi,

I am using this Firefox plugin along with my Synology NAS DS 418j.
Everything work fine on my Windows 10 PCs, but I am also using Linux PCs (mainly Ubuntu 16.04 based Lubuntu and Linux Mint distributions), on which I have issues with the plugin.
Firefox modules and settings are synchronized trough the browser integrated Sync function.

### Versions

**Extension version**: 0.5.3

**Browser and version**: Firefox Quantum 59.0.2 for Ubuntu 16.04

**DSM version**: 6.1.16-15266

**Download Station version**: 3.8.8-3500

### Steps to Reproduce the Issue

1 - Right-clicking on a link shows "Download with DownloadStation" menu entry than I can select, but then a Popup message tells me "Failed to connect to DiskStation - Please check your settings"

2. Select Firefox Modules Management View
3. Select Synology Diownload Manager Preferences.
4. No settings fields available for server, credentials and plugin options specification

5. Left click on Synology Download Manager icon in the menu bar (top right of the browser window)
6. The drop down menu is empty
7. The drop down download list is empty, eventhough there are ongoing downloads (visible from another browser instance running on a Windows 10 PC) => probably because the plugin is not connected to the NAS.

Is this plugin supposed to be functional on linux platforms? Are there any prerequisites or dependencies that I have to install?

Thanks for your help.

**Comment by seansfkelley** [comment]
Thank you for the detailed report! I just published version 0.5.4 which should fix this issue. Please try it out and let me know!

**Comment by seansfkelley** [comment]
Closing as I got confirmation from #83. Feel free to reopen if the issue was not actually fixed for you using addon version 0.5.5 or higher.

**Comment by Audren13** [comment]
Thank you very much. Sorry for my late answer, I was on travel and just back home today.

I can confirm everything is working as expected:
-The settings are now available in the Preference page of Synology Download Manager
- The menu bar as well as the download list are back and functional
- The drop down menu is OK

**Comment by seansfkelley** [comment]
Great, happy to hear it works for you now!
