### ISSUE TITLE
extension appears to be connected but items not getting added to queue

### ISSUE THREAD

**Issue by davidpsharp** [seansfkelley/synology-download-manager#94]
Thanks for filing an issue! I appreciate you taking the time to help improve Synology Download Manager.

- If this if a **feature request**, you can ignore the rest of this text. 
- If this is a **bug report**, please include the following information for a faster and more effective response/fix.

### Versions

**Extension version**: (visible in Synology Download Manager's settings (Firefox) or in the extension list (Chrome))
0.5.4

**Browser and version**: (usually found in the browser's "About")
Google Chrome on MacOS
Chrome Version 68.0.3440.106 (Official Build) (64-bit)
MacOS Sierra v10.12.6

**DSM version**: (DSM > Control Panel > Info Center > General > DSM version)
DSM 6.2-23739 on DS918+

**Download Station version**: (DSM > Package Center > Installed > Download Station > Installed version)
3.8.10-3509

### Steps to Reproduce the Issue

I can't get any links to be added to my download station despite the extension being able to connect to the server.

I've tried clicking on the 'Download with DownloadStation' on the right click menu or clicking on the extension icon and the plus icon to add the URLs manually but nothing works. The extension popup appears in both cases saying 'Adding download...' and stays for a few seconds but then nothing. The URLs are all valid and happily add to the DownloadStation and download if I add them manually in DSM.

I know the extension can communicate with the DownloadStation package because it reports 'Connection Successful!' when I hit the test connection button in the Extension settings and I can also see my shared folder that the user the extension is connecting with has access to in the list of 'download to' locations when I hit the plus sign on the extension panel to add the URLs.

![screen shot 2018-09-05 at 10 27 49](https://user-images.githubusercontent.com/22786950/45085293-3dcca580-b0f8-11e8-9d77-53298d88ab5c.png)
![screen shot 2018-09-05 at 10 27 37](https://user-images.githubusercontent.com/22786950/45085309-43c28680-b0f8-11e8-976e-71b42f47244f.png)

**Comment by davidpsharp** [comment]
I was having another play around having switched to developer mode and just noticed this debug output on the settings window in case relevant....

Redacted extension state: {
  "connection": {
    "hostname": true,
    "password": true,
    "port": true,
    "protocol": "http",
    "username": true
  },
  "lastSevereError": "(omitted for brevity)",
  "notifications": {
    "completionPollingInterval": 60,
    "enableCompletionNotifications": false,
    "enableFeedbackNotifications": true
  },
  "shouldHandleDownloadLinks": false,
  "stateVersion": 3,
  "taskFetchFailureReason": null,
  "taskSortType": "name-asc",
  "tasks": 0,
  "tasksLastCompletedFetchTimestamp": 1536140380538,
  "tasksLastInitiatedFetchTimestamp": 1536140380311,
  "visibleTasks": {
    "completed": true,
    "downloading": true,
    "errored": true,
    "other": true,
    "uploading": true
  }
}

Error: 'Request failed with status code 429'
Error stack trace: Error: Request failed with status code 429
    at createError (chrome-extension://iaijiochiiocodhamehbpmdlobhgghgi/dist/js/background.js:2871:15)
    at settle (chrome-extension://iaijiochiiocodhamehbpmdlobhgghgi/dist/js/background.js:2888:12)
    at XMLHttpRequest.handleLoad (chrome-extension://iaijiochiiocodhamehbpmdlobhgghgi/dist/js/background.js:3215:7)

**Comment by seansfkelley** [comment]
A 429 status code is described as "too many requests" which suggests that your previous attempts or the NAS itself is causing you to get rate limited on the site you're trying to use.

Can you (1) "clear output" in the debugging section and then (2) try using a different site? If it works, great; if it doesn't, can you paste any new debugging output here again?

**Comment by davidpsharp** [comment]
Thanks for your quick response Sean, appreciate you taking a look.

Pressing clear output doesn't appear to do anything on my system, the debug output box was still populated.

I restarted chrome and the debug output was already populated (see output 1 below), not sure if it had persisted or if the extension threw an error on initialisation. I chose a website that I know has no significant download restrictions on number of connections (different one to the previous site) and used the right click menu entry, still no joy so I took a copy of the new output 2 below (timestamp appears different).

Chrome has updated so I'm now on: Version 69.0.3497.81 (Official Build) (64-bit)

Output 1:

Redacted extension state: {
  "connection": {
    "hostname": true,
    "password": true,
    "port": true,
    "protocol": "http",
    "username": true
  },
  "lastSevereError": "(omitted for brevity)",
  "notifications": {
    "completionPollingInterval": 60,
    "enableCompletionNotifications": false,
    "enableFeedbackNotifications": true
  },
  "shouldHandleDownloadLinks": false,
  "stateVersion": 3,
  "taskFetchFailureReason": null,
  "taskSortType": "name-asc",
  "tasks": 0,
  "tasksLastCompletedFetchTimestamp": 1536224487714,
  "tasksLastInitiatedFetchTimestamp": 1536224486480,
  "visibleTasks": {
    "completed": true,
    "downloading": true,
    "errored": true,
    "other": true,
    "uploading": true
  }
}

Error: 'Request failed with status code 429'
Error stack trace: Error: Request failed with status code 429
    at createError (chrome-extension://iaijiochiiocodhamehbpmdlobhgghgi/dist/js/background.js:2871:15)
    at settle (chrome-extension://iaijiochiiocodhamehbpmdlobhgghgi/dist/js/background.js:2888:12)
    at XMLHttpRequest.handleLoad (chrome-extension://iaijiochiiocodhamehbpmdlobhgghgi/dist/js/background.js:3215:7)




Output 2:

Redacted extension state: {
  "connection": {
    "hostname": true,
    "password": true,
    "port": true,
    "protocol": "http",
    "username": true
  },
  "lastSevereError": "(omitted for brevity)",
  "notifications": {
    "completionPollingInterval": 60,
    "enableCompletionNotifications": false,
    "enableFeedbackNotifications": true
  },
  "shouldHandleDownloadLinks": false,
  "stateVersion": 3,
  "taskFetchFailureReason": null,
  "taskSortType": "name-asc",
  "tasks": 0,
  "tasksLastCompletedFetchTimestamp": 1536224627931,
  "tasksLastInitiatedFetchTimestamp": 1536224627707,
  "visibleTasks": {
    "completed": true,
    "downloading": true,
    "errored": true,
    "other": true,
    "uploading": true
  }
}

Error: 'Request failed with status code 429'
Error stack trace: Error: Request failed with status code 429
    at createError (chrome-extension://iaijiochiiocodhamehbpmdlobhgghgi/dist/js/background.js:2871:15)
    at settle (chrome-extension://iaijiochiiocodhamehbpmdlobhgghgi/dist/js/background.js:2888:12)
    at XMLHttpRequest.handleLoad (chrome-extension://iaijiochiiocodhamehbpmdlobhgghgi/dist/js/background.js:3215:7)




Redacted extension state: {
  "connection": {
    "hostname": true,
    "password": true,
    "port": true,
    "protocol": "http",
    "username": true
  },
  "lastSevereError": "(omitted for brevity)",
  "notifications": {
    "completionPollingInterval": 60,
    "enableCompletionNotifications": false,
    "enableFeedbackNotifications": true
  },
  "shouldHandleDownloadLinks": false,
  "stateVersion": 3,
  "taskFetchFailureReason": null,
  "taskSortType": "name-asc",
  "tasks": 0,
  "tasksLastCompletedFetchTimestamp": 1536224627931,
  "tasksLastInitiatedFetchTimestamp": 1536224627707,
  "visibleTasks": {
    "completed": true,
    "downloading": true,
    "errored": true,
    "other": true,
    "uploading": true
  }
}

Error: 'Request failed with status code 429'
Error stack trace: Error: Request failed with status code 429
    at createError (chrome-extension://iaijiochiiocodhamehbpmdlobhgghgi/dist/js/background.js:2871:15)
    at settle (chrome-extension://iaijiochiiocodhamehbpmdlobhgghgi/dist/js/background.js:2888:12)
    at XMLHttpRequest.handleLoad (chrome-extension://iaijiochiiocodhamehbpmdlobhgghgi/dist/js/background.js:3215:7)

**Comment by davidpsharp** [comment]
In case relevant, the only other extensions I have installed and active are Adblock Plus, LastPass, Private Internet Access (VPN proxy, not in use), OneTab, Google Keep.

**Comment by seansfkelley** [comment]
Thanks for all the debugging information! Weird that clearing the output doesn't do anything, but I can't reproduce that particular issue. Due to the changing timestamp it's clearly logging new errors though, so at least that. Unfortunately I don't log where the request is going, so it's hard to narrow down what the issue could be.

I filed #95 to improve the logging here, but there's nothing I can see to do to help you before then. The only thing I can think of is to try uninstalling and reinstalling the extension, or a different browser, to see if the error persists. :/

**Comment by seansfkelley** [comment]
Hey @davidpsharp, are you still seeing this issue? The latest version of the extension includes more detailed logging that could help narrow down the issue.
