### ISSUE TITLE
Empty downloads / Error updating tasks (Multi-account containers?)

### ISSUE THREAD

**Issue by Riekr** [seansfkelley/synology-download-manager#98]
Preface is I'm using multi account containers from firefox as I do from a lot of time.
Today pressing the button of synology download manager starting to show an empty box with the message "Error updating tasks". Usually when this happens it is enough to login to the web interface and restart firefox (after having selected the default container) to have it working again.

### Versions
**Extension version**: 0.5.6
**Browser and version**: Firefox 63.0.3
**DSM version**: DSM 6.2.1-23824 Update 1
**Download Station version**: 3.8.12-3518

### Steps to Reproduce the Issue

1. Open firefox
2. Open sdm popup
3. sdm popup is empty

### Debugging output:

Redacted extension state: {
  "connection": {
    "protocol": "https",
    "hostname": true,
    "port": true,
    "username": true,
    "password": true
  },
  "visibleTasks": {
    "downloading": true,
    "uploading": true,
    "completed": true,
    "errored": true,
    "other": true
  },
  "taskSortType": "completed-percent-desc",
  "notifications": {
    "enableFeedbackNotifications": true,
    "enableCompletionNotifications": false,
    "completionPollingInterval": 60
  },
  "shouldHandleDownloadLinks": true,
  "tasks": 0,
  "taskFetchFailureReason": {
    "failureMessage": "Destination does not exist."
  },
  "tasksLastInitiatedFetchTimestamp": 1543351715798,
  "tasksLastCompletedFetchTimestamp": 1543351715803,
  "lastSevereError": "(omitted for brevity)",
  "stateVersion": 3
}

TypeError: 'response.error is undefined'
Error stack trace: testConnection/<@moz-extension://3056e062-1526-41d8-9654-4dd6865b1bdb/dist/js/settings.js:24715:22

**Comment by seansfkelley** [comment]
Hm, I haven't used multi account containers myself so I'm not totally familiar with how they work.

I see that the last error it reported was "destination does not exist". That's an error from the Synology itself, indicating that it is indeed reaching the NAS, but the NAS is responding with an error. I thought that error code was used only when you tried to add a new upload, but here it looks like that error is coming back when you try to load the list of tasks, which I have never seen before. "Destination" generally refers to the location to which you're downloading something; did you recently rename/delete/otherwise modify the folders you use for downloading? Maybe you accidentally put one of your tasks into an invalid state which is causing the load to fail?

If you open the extension popup, do you see the spinner on the top left indicating it's trying to load again?

**Comment by Riekr** [comment]
Hi,
 no recent modifications or whatsoever, I only have some emule downloads
active. The strange thing is that here at office it now works with same
software versions but firefox for osx instead of w10, I'll check again at
home if it was a temporary fail or if the problem persists (even tough I
was able to access download station via web interface yesterday).
 What happened is: started firefox, i see colored button without download
counter, after a while the button goes gray and clicking it shows the
reported message.
 Regarding containers: to test you can simply install an extension and then
create a container for your nas domain/ip, once accessing it you will be
prompted by an extension page on which container to use. It's a nice way to
access the nas with both admin and user account at the same time without
bothering with logins.
 I don't have an antivirus at home but windows defender.

Il giorno mer 28 nov 2018 alle ore 07:55 Sean Kelley <
notifications@github.com> ha scritto:

**Comment by seansfkelley** [comment]
Do you mean that the same host/port/username/password combination that it works one one computer but not another? That is very mysterious. If that's the case, the only thing I can think of is that the extension got into a weird state. Can you try removing it and reinstalling it? If that fixes the problem it'll help narrow down what could be causing it.

**Comment by Riekr** [comment]
At home the extension disappeared, maybe firfox sync lost some piece from
work. In the end I reinstalled the extension, opened the web interface,
logged out, relogged in inserting the otp and everything worked as expected.

Il giorno gio 29 nov 2018 alle ore 09:27 Gianluca Parmiggiani <
gparmiggiani@gmail.com> ha scritto:

**Comment by greglap** [comment]
Recently ran into the "Error updating tasks" issue as well.

Extension version: 0.5.6
Browser and version: Firefox 63.0.3
DSM version: DSM 6.1.4-15217 Update 1

Interestingly going to the extension settings and clicking "Test Connection" worked just fine. But the UI button would still error out.

Just now I tried disabling/enabling the extension in the "Add-ons" page and it immediately reconnected and loaded the pending/completed downloads from the DS.

**Comment by seansfkelley** [comment]
Hm, both of those are strange, but probably related to how the extension manages the logged-in session. I'm going to close this issue out since it seems to have resolved itself, but I've opened #101 to see if there's anything special I need to do to support multi-account containers.
