### ISSUE TITLE
connection issues

### ISSUE THREAD

**Issue by thatman84** [seansfkelley/synology-download-manager#99]
I am new to synology and this extension.

I am getting connection error in the addon options. What should I be putting there? local IP address of synology?
Anything that should be enabled 

### Versions

**Extension version**: 0.5.6
Firefox 64.0

DSM 6.2.1-23824 Update 4

Download Station 3.8.12-3518

**Comment by thatman84** [comment]
Please ignore

Changed port to http 5000 and all is ok

I was unaware of the certificate thing for https

**Comment by seansfkelley** [comment]
Glad you figured it out! There's plenty of information around about how to set up your own cert and make your browser trust it, which should allow the extension to trust it as well.
